### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by gwillz** [ukrbublik/shm-typed-array#3]
FWIW, I wrote these for one of my projects. It may help others.

https://gist.github.com/gwillz/bf06ab4844541d8617b080bdbae08109

**Comment by ukrbublik** [comment]
Can you create PR for this?

**Comment by gwillz** [comment]
Sure can!
Just figuring out some tests.

**Comment by ukrbublik** [comment]
Merged! Thanks!
